Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Samsung LED TV 39 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '580',
	new_price: '520',
	price_off: '60',
	percent_off: '10',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE39ES6720 LED HD 1080p 3D Smart TV, 39 Inch with Freeview/Freesat HD, White',
	screen_size: 39, 
	tv_type:'LED',
	model_no: 'UE39ES6720' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Samsung LED TV 37 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9135189_R_SET?$Listers$',
	product_type:'television',
	old_price: '550',
	new_price: '500',
	price_off: '50',
	percent_off: '9',
	retailler: 'John Lewis',
	make: 'Samsung',
	description: 'Samsung UE37ES6710 LED HD 1080p 3D Smart TV, 37 Inch with Freeview/Freesat HD, White',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'UE37ES6710' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Panasonic LED TV 35 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/9159079_R_SET?$Listers$',
	product_type:'television',
	old_price: '500',
	new_price: '450',
	price_off: '50',
	percent_off: '10',
	retailler: 'Argos',
	make: 'Panasonic',
	description: 'Pansonic XS123456 LED HD 1080p 3D Smart TV, 35 Inch with Freeview/Freesat HD, Black',
	screen_size: 34, 
	tv_type:'LED',
	model_no: 'XS123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)
Product.create!(title: 'Sony Plasma TV 40 Inch"',
	link_url:'http://www.argos.co.uk/static/Product/partNumber/9135189.htm',
	image_url:'http://argos.scene7.com/is/image/Argos/5299847_R_SET?$Listers$',
	product_type:'television',
	old_price: '600',
	new_price: '500',
	price_off: '100',
	percent_off: '17',
	retailler: 'Argos',
	make: 'Sony',
	description: 'Sony SO123456 Plasma HD 1080p 3D TV, 40 Inch with Freeview/Freesat HD, White',
	screen_size: 40, 
	tv_type:'Plasma',
	model_no: 'SO123456' 
	)



